export default [
  { title: "A", id: 1 },
  { title: "Am", id: 2 },
  { title: "A#", id: 3 },
  { title: "A#m", id: 4 },
  { title: "B", id: 5 },
  { title: "Bm", id: 6 },
  { title: "C", id: 7 },
  { title: "Cm", id: 8 },
  { title: "C#", id: 9 },
  { title: "C#m", id: 10 },
  { title: "D", id: 11 },
  { title: "Dm", id: 12 },
  { title: "D#", id: 13 },
  { title: "D#m", id: 14 },
  { title: "E", id: 15 },
  { title: "Em", id: 16 },
  { title: "F", id: 17 },
  { title: "Fm", id: 18 },
  { title: "F#", id: 19 },
  { title: "F#m", id: 20 },
  { title: "G", id: 21 },
  { title: "G#m", id: 22 },
];
